### ISSUE TITLE
facebook standard error

### ISSUE THREAD

**Issue by greyxhood** [DarkSecDevelopers/HiddenEye#153]
page works but when i enter credentials this is the output:
Traceback (most recent call last):
  File "HiddenEye.py", line 32, in <module>
    getCredentials()
  File "/root/HiddenEye/Defs/Actions.py", line 304, in getCredentials
    ip = re.match('User Public IP: (.*?)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by alienwaresoldier** [comment]
Same issue Traceback (most recent call last):
  File "HiddenEye.py", line 32, in <module>
    getCredentials()
  File "/home/aliensoldier/HiddenEye/Defs/Actions.py", line 304, in getCredentials
    ip = re.match('User Public IP: (.*?)\n', lines).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
┌─[✗]─[aliensoldier@parrot]─[~/HiddenEye]

**Comment by usama7628674** [comment]
@alienwaresoldier @greyxhood It's fixed.Clone the tool again or do `git pull`

**Comment by clizSec** [comment]
Same issue
