### ISSUE TITLE
Not working over ssh?

### ISSUE THREAD

**Issue by softdream1981** [DarkSecDevelopers/HiddenEye#173]
Over ssh i got this error:
Traceback (most recent call last):
  File "HiddenEye.py", line 26, in <module>
    runMainMenu()
  File "/root/HiddenEye/Defs/Actions.py", line 152, in runMainMenu
    ''').format(GREEN, DEFAULT, CYAN, RED))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 174-175: ordinal not in range(128)

**Comment by An0nUD4Y** [comment]
@softdream1981 , Which Platform You are Using ? Please Give More Info ??

**Comment by softdream1981** [comment]
I use Kali linux VPS over SSH.

**Comment by sTiKyt** [comment]
@softdream1981 i think SSH main problem..

**Comment by usama7628674** [comment]
@sTiKyt @softdream1981 I'll fix this soon.

**Comment by argtje99** [comment]
Same error right here. Working from OneplusOne 64gb Nethunter

Last login: Sun Dec 30 21:59:21 UTC 2018 on pts/5
Linux kali 3.4.112-cyanogenmod-g8fbc62e #3 SMP PREEMPT Fri ATraceback (most recent call last):
  File "HiddenEye.py", line 26, in <module>
    runMainMenu()                                             File "/root/HiddenEye/Defs/Actions.py", line 152, in runMainMenu                                                          ''').format(GREEN, DEFAULT, CYAN, RED))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 174-175: ordinal not in range(128)
root@kali:~/HiddenEye#

**Comment by usama7628674** [comment]
@softdream1981 @argtje99 Do what @hxrofo said.

**Comment by argtje99** [comment]
Thanks that's the trick 👍 But now python uses the UTF8 codec instead of Ascii? Is there another solution then adding the UTF8 in the .bashrc? Thankyou

**Comment by argtje99** [comment]
Found the permanent solution! By running: dpkg-reconfigure locales 
Then select: "All locales" Then select "en_US.UTF-8"
After that reboot your machine. Then open terminal and run the command: "locale"
Then you see that "en_US.UTF-8" is the default language. Instead of POSIX.
