### ISSUE TITLE
Termux issues (no module wget)

### ISSUE THREAD

**Issue by daredevil12345** [DarkSecDevelopers/HiddenEye#186]
upon running HiddenEye.py on termux it show an error

 ` $ python2 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request
$ python HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'
$    `

**Comment by An0nUD4Y** [comment]
@daredevil12345  , Install it again from those commands in [instructions.md](https://github.com/DarkSecDevelopers/HiddenEye/blob/master/instructions.md) ....

**Comment by daredevil12345** [comment]
i followed the RUNNING ON CODE INSTALLATION

for one time it works and run the script perfectly  but when i do on a new session and do Python HiddenEye.py it dosent worked and error is same.

what could be issue? how to solve this? 

fatal: destination path 'HiddenEye' already exists and is not an empty directory.
$ chmod 777 HiddenEye.py && python HiddenEye.py
Successful connection!
Traceback (most recent call last):
  File "HiddenEye.py", line 15, in <module>
    checkPermissions()
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Checks.py", line 59, in checkPermissions
    raise PermissionError("{0}Permissions denied! Please run as '{1}sudo{0}'".format(RED, GREEN))
PermissionError: Permissions denied! Please run as 'sudo'
$
