### ISSUE TITLE
slove the error

### ISSUE THREAD

**Issue by Ranjithkumar567** [DarkSecDevelopers/HiddenEye#189]
chmod +x HiddenEye.py 
root@kali:~/Desktop/HiddenEye# python3 HiddenEye.py 
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/Desktop/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by An0nUD4Y** [comment]
@Ranjithkumar567  , its already resolved please check  #172
