### ISSUE TITLE
Serveo error after link generated.

### ISSUE THREAD

**Issue by jepunband** [DarkSecDevelopers/HiddenEye#207]
[*] SERVEO URL: http://iduser.secure.serveo.net

Traceback (most recent call last):
  File "./HiddenEye.py", line 33, in <module>
    selectServer()
  File "/root/HiddenEye/Defs/Actions.py", line 96, in selectServer
    runServeo()
  File "/root/HiddenEye/Defs/Actions.py", line 140, in runServeo
    data = urlopen("http://tinyurl.com/api-create.php?url="+url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Not Available
root@kali:~/HiddenEye#

**Comment by eMgniK** [comment]
I am getting this same issue on 2 separate Ubuntu OS.

**Comment by jepunband** [comment]
yup it's not fixed yet.

**Comment by eMgniK** [comment]
@sTiKyt do you have any idea what is causing this? I was running a version that was perfectly fine then coming back to using it I'm greeted by this error. I come to believe it is a problem creating a tinyurl link as they have started to prohibit the use of serveo being shortened.

This means this is not a code bug but a server based error of sort.

**Comment by eMgniK** [comment]
@sTiKyt Issue is solved after latest push. Was correct about TinyURL not working. Please close the issue! Cheers
