### ISSUE TITLE
What's the problem and how to resolve?

### ISSUE THREAD

**Issue by Pranay1004** [DarkSecDevelopers/HiddenEye#254]
Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by An0nUD4Y** [comment]
@Pranay1004  Don't Be lazy man...
We have already solved this shit issue ...
Please check closed issues...
#178 #189 #186 #172 #196
