### ISSUE TITLE
not run hidden eye

### ISSUE THREAD

**Issue by abhibadshah1** [DarkSecDevelopers/HiddenEye#291]
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/root/Desktop/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by An0nUD4Y** [comment]
Check closed issues...
