### ISSUE TITLE
Hiddeneye got error

### ISSUE THREAD

**Issue by sneh2698** [DarkSecDevelopers/HiddenEye#323]
Traceback (most recent call last):
  File "HiddenEye.py", line 10, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'

**Comment by sneh2698** [comment]
hiddeneye didn't start and stopped here, now, tell me what to do ?

**Comment by Bartixxx32** [comment]
can confirm that

**Comment by usama7628674** [comment]
@sTiKyt Would you please check on this issue since the last commit might have something to do with it?

**Comment by sTiKyt** [comment]
@sneh2698 just delete your Config.ini

**Comment by sTiKyt** [comment]
@Bartixxx32 just delete config.ini

**Comment by sTiKyt** [comment]
#325
