### ISSUE TITLE
hurray! internet is available....

### ISSUE THREAD

**Issue by tokiijnr** [DarkSecDevelopers/HiddenEye#325]
root@kali:~/HiddenEye# python3 HiddenEye.py

HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "HiddenEye.py", line 10, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'
root@kali:~/HiddenEye#

**Comment by sTiKyt** [comment]
@tokiijnr please delete Config.ini and try again

**Comment by An0nUD4Y** [comment]
@tokiijnr , Create a empty file named " Config.ini " inside the HiddenEye Folder , remember folder name is Case Sensitive.
It May help You to Overcome This issue.
