### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Bartixxx32** [DarkSecDevelopers/HiddenEye#343]
Error when oppening at start of the program
```
HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "/root/HiddenEye/HiddenEye.py", line 10, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/local/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'
```

**Comment by sTiKyt** [comment]
#327

**Comment by sTiKyt** [comment]
#323 #325
