### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by mortaza01** [DarkSecDevelopers/HiddenEye#360]
[*] Waiting For Victim Interaction. Keep Eyes On Requests Coming From Victim ...

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "HiddenEye.py", line 38, in <module>
    getCredentials()
  File "/data/data/com.termux/files/home/HiddenEye/Defs/Actions.py", line 560, in getCredentials
    resp = urlopen('https://ipinfo.io/{0}/json'.format(ip))
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by KathanP19** [comment]
have you done chmod 777 HiddenEye Whole Directory?

**Comment by mortaza01** [comment]
sloved....thank you....
