### ISSUE TITLE
i have this erorr 

### ISSUE THREAD

**Issue by ahmedfox1** [DarkSecDevelopers/HiddenEye#375]
i dont know why i cant open hiddeneye bec this erorr code

HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "./HiddenEye.py", line 15, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'

**Comment by An0nUD4Y** [comment]
@ahmedfox1 , Just relaunch the script , it will start working.

**Comment by KathanP19** [comment]
Just Follow the Installation Instruction @ahmedfox1

**Comment by sTiKyt** [comment]
@ahmedfox1 delete .ini files and try again.

**Comment by An0nUD4Y** [comment]
Closing Here , Feel Free to Reopen...
