### ISSUE TITLE
Termux HiddenEye problem

### ISSUE THREAD

**Issue by Giovsss** [DarkSecDevelopers/HiddenEye#394]
I have this error code in Termux when I try to launch HiddenEye

AY!! Internet is available.. We can Continue Traceback (most recent call last): File "HiddenEye.py", line 15, in <module> from Defs.Actions import *
File "/data/data/com.termux/files/home/HiddenEye/HiddenEye/HiddenEye/HiddenEye/Defs/Actions.py", line 28, in <module>
colorTheme = colorSelector()
File "/data/data/com.termux/files/home/HiddenEye/HiddenEye/HiddenEye/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
if config.get("Defaults", "theme") == "anaglyph":
File "/data/data/com.termux/files/usr/lib/python3.7/configparser.py", line 780, in get
d = self._unify_values(section, vars)
File "/data/data/com.termux/files/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'

**Comment by An0nUD4Y** [comment]
Just relaunch the script , Error will be fixed automatically.
