### ISSUE TITLE
Issuse while using localxpose

### ISSUE THREAD

**Issue by joseph-sebastian720** [DarkSecDevelopers/HiddenEye#449]
Traceback (most recent call last):
  File "./HiddenEye.py", line 47, in <module>
    selectServer(port)
  File "/root/Downloads/HiddenEye-master(1)/HiddenEye-master/Defs/Actions.py", line 180, in selectServer
    runLocalxpose(port)
  File "/root/Downloads/HiddenEye-master(1)/HiddenEye-master/Defs/Actions.py", line 230, in runLocalxpose
    randomLocalxpose(port)
  File "/root/Downloads/HiddenEye-master(1)/HiddenEye-master/Defs/Actions.py", line 283, in randomLocalxpose
    url = str(output).decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

**Comment by Moltivie** [comment]
@joseph-sebastian720 fixed. PL (#450).
