### ISSUE TITLE
Python HiddenEye .py error on Kali Linux?

### ISSUE THREAD

**Issue by lulzsecind** [DarkSecDevelopers/HiddenEye#503]
Traceback (most recent call last):                        File "HiddenEye.py", line 7, in <module>                  from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 634      SyntaxError: Non-ASCII character '\xe2' in file /root/HiddenEye/Defs/Actions.py on line 635, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by An0nUD4Y** [comment]
@lulzsecind , Fix is already available for this error .
Check At The Bottom of Readme file https://github.com/DarkSecDevelopers/HiddenEye/blob/master/README.md

**Comment by usama7628674** [comment]
@lulzsecind See here https://github.com/DarkSecDevelopers/HiddenEye/blob/master/README.md#ascii-error-fix

**Comment by sibinms** [comment]
Traceback (most recent call last):                                                                                                                                    
  File "HiddenEye.py", line 45, in <module>                                                                                                                           
    server_runner.server_selection(port)                                                                                                                              
  File "/home/sibin/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                                               
    NgrokController().establish_connection(port=port)                                                                                                                 
  File "/home/sibin/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection                                                                      
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)                                                                     
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect                                                                                
    api_url = get_ngrok_process(pyngrok_config).api_url                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process                                                                      
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                                                                                                                 
AttributeError: 'str' object has no attribute 'ngrok_path'

I got error like this while selected Ngrok server
