### ISSUE TITLE
Traceback/SSL Error

### ISSUE THREAD

**Issue by N3X4** [DarkSecDevelopers/HiddenEye#536]
[*] Downloading Localxpose...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/contrib/pyopenssl.py", line 462, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)                                                           
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])",)    
                                                                                                          
During handling of the above exception, another exception occurred:                                       
                                                                                                          
Traceback (most recent call last):                                                                        
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send                   
    timeout=timeout                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen           
    _stacktrace=sys.exc_info()[2])                                                                        
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment             
    raise MaxRetryError(_pool, url, error or ResponseError(cause))                                        
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='lxpdownloads.sgp1.digitaloceanspaces.com', port=443): Max retries exceeded with url: /cli/loclx-linux-amd64.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))                             
                                                                                                          
During handling of the above exception, another exception occurred:                                       
                                                                                                          
Traceback (most recent call last):                                                                        
  File "HiddenEye.py", line 27, in <module>                                                               
    checkLocalxpose()                                                                                     
  File "/home/kali/HiddenEye/Defs/Checks.py", line 160, in checkLocalxpose                                
    req = requests.get(url)                                                                               
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 75, in get                          
    return request('get', url, params=params, **kwargs)                                                   
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 60, in request                      
    return session.request(method=method, url=url, **kwargs)                                              
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 524, in request                
    resp = self.send(prep, **send_kwargs)                                                                 
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 637, in send                   
    r = adapter.send(request, **kwargs)                                                                   
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 514, in send                   
    raise SSLError(e, request=request)                                                                    
requests.exceptions.SSLError: HTTPSConnectionPool(host='lxpdownloads.sgp1.digitaloceanspaces.com', port=443): Max retries exceeded with url: /cli/loclx-linux-amd64.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))           

This is the error I keep getting.

**Comment by An0nUD4Y** [comment]
#525
