### ISSUE TITLE
errors during installation

### ISSUE THREAD

**Issue by dorianus1992** [DarkSecDevelopers/HiddenEye#562]
Hey,

This is the error message after i run sudo python3 HiddenEye.py

[>] Checking For Updates...
[+] [Up-To-Date]- v 0.5.3
 * PHP INSTALLATION FOUND
[*] Ngrok Not Found !!
[*] Downloading Ngrok...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4c1018760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
                                                                                               
During handling of the above exception, another exception occurred:                            
                                                                                               
Traceback (most recent call last):                                                             
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send                
    resp = conn.urlopen(                                                                       
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen        
    retries = retries.increment(                                                               
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment          
    raise MaxRetryError(_pool, url, error or ResponseError(cause))                             
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bin.equinox.io', port=443): Max retries exceeded with url: /c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4c1018760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))                           
                                                                                               
During handling of the above exception, another exception occurred:                            
                                                                                               
Traceback (most recent call last):                                                             
  File "HiddenEye.py", line 28, in <module>                                                    
    checkNgrok()                                                                               
  File "/home/dorianpro/HiddenEye/Defs/Checks.py", line 93, in checkNgrok                      
    req = requests.get(url)                                                                    
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get                       
    return request('get', url, params=params, **kwargs)                                        
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request                   
    return session.request(method=method, url=url, **kwargs)                                   
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request             
    resp = self.send(prep, **send_kwargs)                                                      
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send                
    r = adapter.send(request, **kwargs)                                                        
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send                
    raise ConnectionError(e, request=request)                                                  
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bin.equinox.io', port=443): Max retries exceeded with url: /c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4c1018760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Can you guys assist with this matter?

**Comment by An0nUD4Y** [comment]
Please Try Cloning Again with Latest commits.

Reopen Issue , if solution not worked.
