### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by MaksymHnatkov** [DarkSecDevelopers/HiddenEye#610]
Can you help me with this?

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/kali/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/kali/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in <module>
    import Defs.ActionManager.Server.server_menu as server_menu
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 19, in <module>
    enter_server_www = chdir("Server/www")
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'

**Comment by catekuser** [comment]
> Can you help me with this?
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 8, in
> import Defs.ActionManager.main_runner as main_runner
> File "/home/kali/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in
> import Defs.ActionManager.simple_informant as simple_informant
> File "/home/kali/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in
> import Defs.ActionManager.Server.server_menu as server_menu
> File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in
> import Defs.ActionManager.Server.server_runner as server_runner
> File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 19, in
> enter_server_www = chdir("Server/www")
> FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'


Hi,

I have the same issue, how did you fix this, thanks.

**Comment by catekuser** [comment]
python3 HiddenEye.py 
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/root/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/root/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in <module>
    import Defs.ActionManager.Server.server_menu as server_menu
  File "/root/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 19, in <module>
    enter_server_www = chdir("Server/www")
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'

ANy help?

**Comment by MaksymHnatkov** [comment]
Hi! I closed issue 'cause some guy made the same before me. Unfortunatly no
help yet.

вт, 26 трав. 2020, 19:28 користувач catekuser <notifications@github.com>
пише:

**Comment by catekuser** [comment]
Thank you for your reply. I also opened as a new issue.

**Comment by catekuser** [comment]
Solved. You need to create the folder manually:

cd HiddenEye
mkdir Server/www

**Comment by MaksymHnatkov** [comment]
Thank you!!!

вт, 26 трав. 2020, 19:45 користувач catekuser <notifications@github.com>
пише:

**Comment by darkmidus** [comment]
@MaksymHnatkov We have fixed the issue, update and it should work.
