### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'

### ISSUE THREAD

**Issue by catekuser** [DarkSecDevelopers/HiddenEye#615]
Hi
I receive the following error. Any help?

python3 HiddenEye.py
Traceback (most recent call last):
File "HiddenEye.py", line 8, in
import Defs.ActionManager.main_runner as main_runner
File "/root/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in
import Defs.ActionManager.simple_informant as simple_informant
File "/root/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in
import Defs.ActionManager.Server.server_menu as server_menu
File "/root/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in
import Defs.ActionManager.Server.server_runner as server_runner
File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 19, in
enter_server_www = chdir("Server/www")
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'

Thanks

**Comment by catekuser** [comment]
Solved. Create the folder manually.
cd HiddenEye/
mkdir Server/www
