### ISSUE TITLE
using unbuntu 16 server from hostinger

### ISSUE THREAD

**Issue by Frosty4819** [DarkSecDevelopers/HiddenEye#620]
when u go to open it with python3 HiddenEye.py i get this error 

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/root/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/root/HiddenEye/Defs/ActionManager/simple_informant.py", line 10, in <module>
    import Defs.FeatureManager.EmailManager.email_prompt as email_prompt
  File "/root/HiddenEye/Defs/FeatureManager/EmailManager/email_prompt.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

**Comment by darkmidus** [comment]
Hmm, thats weird. Did you try to run it as sudo?

**Comment by Frosty4819** [comment]
Yes do u have discord? Cause it doesn't work

**Comment by Frosty4819** [comment]
Before this got taken down it would have an error where it couldn't read a asci text Art so I had to go in edit that so it didn't show that but now it doesn't work at all unusual

**Comment by Frosty4819** [comment]
ok so i pulled a big brain move and download the master file when it was version 5.3 on a usb before it got taken down so there are no problems with the old version its just 5.4

**Comment by sTiKyt** [comment]
You should be filling it templates when you create issue. We don't know your machine, python version, OS, nothing... You just throw errors at us...

**Comment by Frosty4819** [comment]
my bad it is a vps server hosted by hostinger with unbuntu 16.04 64bit and latest python version

**Comment by sTiKyt** [comment]
@Frosty4819 Updated HiddenEye, did that fix problem for you?
