### ISSUE TITLE
[DUPLICATE] Traceback HiddenEye NGROK

### ISSUE THREAD

**Issue by AhsanDz** [DarkSecDevelopers/HiddenEye#646]
[ NGROK SERVER ]!
-------------------------------
Traceback (most recent call last):
  File "HiddenEye.py", line 49, in <module>
    server_menu.server_selection(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 47, in server_selection
    server_runner.start_ngrok(port) # FIXED
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 100, in start_ngrok
    ngrok.connect(port)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 135, in get_ngrok_process                               return process.get_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 147, in get_process
    return _start_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 270, in _start_process                                raise PyngrokNgrokError("The ngrok process errored on start.", ngrok_process.startup_logs,
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start.

**Comment by AhsanDz** [comment]
![Termux_Screenshot_2020 05 31_16 02 20](https://user-images.githubusercontent.com/66170812/83347542-4a773f80-a358-11ea-835f-784abe55191c.jpg)
Termux

**Comment by sTiKyt** [comment]
#632
