### ISSUE TITLE
[QUESTION] How to install pyngrok?

### ISSUE THREAD

**Issue by aadi-1111** [DarkSecDevelopers/HiddenEye#655]
I got this error. What to do now?...

Traceback (most recent call last):
File "HiddenEye.py", line 8, in 
import Defs.ActionManager.main_runner as main_runner
File "/home/aditya1111/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in 
from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
File "/home/aditya1111/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in 
from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok

**Comment by darkmidus** [comment]
In order to use HiddenEye, you need pyngrok. Install it with the compand: pip install pyngrok or pip3 install pyngrok
