### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ankit9525** [DarkSecDevelopers/HiddenEye#731]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok
    download_path = _download_file(url, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 167, in _download_file
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 158, in _download_file
    shutil.copyfileobj(response, f)
  File "/usr/lib/python3.8/shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HiddenEye.py", line 48, in <module>
    server_runner.server_selection(port)
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection
    start_ngrok(port)  # FIXED
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok
    ngrok.connect(port=int(port))
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
    ensure_ngrok_installed(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
    install_ngrok(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: The read operation timed out

**Comment by darkmidus** [comment]
Please fill in the rest of the template

**Comment by ankit9525** [comment]
pllz tell me the command
i'm noob

**Comment by ankit9525** [comment]
[ NGROK SERVER ]! 
-------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok
    download_path = _download_file(url, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 147, in _download_file
    response = urlopen(url, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1091: The handshake operation timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HiddenEye.py", line 48, in <module>
    server_runner.server_selection(port)
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection
    start_ngrok(port)  # FIXED
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok
    ngrok.connect(port=int(port))
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
    ensure_ngrok_installed(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
    install_ngrok(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: <urlopen error _ssl.c:1091: The handshake operation timed out>
