### ISSUE TITLE
please help me..!!!

### ISSUE THREAD

**Issue by ankit9525** [DarkSecDevelopers/HiddenEye#740]
![Screenshot at 2020-07-28 21-35-43](https://user-images.githubusercontent.com/63737981/88691457-68f57f00-d0ec-11ea-90c5-0e6f3ec8b9e8.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Python [e.g. 3.6.1]
 - HiddenEye Version [e.g. 1.0.22]

**Additional context**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 102, in install_ngrok
    download_path = _download_file(url, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 167, in _download_file
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 158, in _download_file
    shutil.copyfileobj(response, f)
  File "/usr/lib/python3.8/shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HiddenEye.py", line 48, in <module>
    server_runner.server_selection(port)
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 50, in server_selection
    start_ngrok(port)  # FIXED
  File "/home/ankit/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 161, in start_ngrok
    ngrok.connect(port=int(port))
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 183, in connect
    api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 133, in get_ngrok_process
    ensure_ngrok_installed(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 81, in ensure_ngrok_installed
    install_ngrok(ngrok_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/installer.py", line 110, in install_ngrok
    raise PyngrokNgrokInstallError("An error occurred while downloading ngrok from {}: {}".format(url, e))
pyngrok.exception.PyngrokNgrokInstallError: An error occurred while downloading ngrok from https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip: The read operation timed out

**Comment by Vedant-Bhalgama** [comment]
I am getting the same error!

**Comment by Vedant-Bhalgama** [comment]
Can anyone help me please? No support is there from your side !

**Comment by sTiKyt** [comment]
> Can anyone help me please? No support is there from your side !

Check if your HiddenEye has internet connection

**Comment by sTiKyt** [comment]
Also don't name issues like that or you'll be ignored and issue is going to be deleted

**Comment by sTiKyt** [comment]
You didn't show whole error
