### ISSUE TITLE
[BUG] ngrok connection error

### ISSUE THREAD

**Issue by rufatsamadov** [DarkSecDevelopers/HiddenEye#762]
Hi guys .When i try to connect ngrok server i get this error? Could you please help me?

t=2020-08-13T14:53:16+0000 lvl=warn msg="failed to get home directory, using $HOME instead" err="user: Current not implemented on linux/arm64" $HOME=/data/data/com.termux/files/home
t=2020-08-13T14:53:16+0000 lvl=warn msg="can't bind default web address, trying alternatives" obj=web addr=127.0.0.1:4040                                                       t=2020-08-13T14:53:16+0000 lvl=eror msg="failed to reconnect session" obj=csess id=2a64614eef7f err="dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:40541->[::1]:53: read: connection refused"
Traceback (most recent call last):
  File "HiddenEye.py", line 49, in <module>                                                 server_menu.server_selection(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 47, in server_selection                                                          server_runner.start_ngrok(port) # FIXED                                               File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_ngrok                                                            ngrok.connect(port=int(port))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 183, in connect                                                                         api_url = get_ngrok_process(ngrok_path, config_path, auth_token, region).api_url
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/ngrok.py", line 135, in get_ngrok_process                                                               return process.get_process(ngrok_path, config_path, auth_token, region)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 206, in get_process                                                                   return _start_process(ngrok_path, config_path, auth_token, region)                    File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pyngrok/process.py", line 329, in _start_process
    raise PyngrokNgrokError("The ngrok process errored on start: {}.".format(ngrok_process.startup_error),                                                                      pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:40541->[::1]:53: read: connection refused.

![WhatsApp Image 2020-08-13 at 19 00 26](https://user-images.githubusercontent.com/63500334/90151251-90f50b80-dd97-11ea-9214-c731117327f0.jpeg)

**Comment by sTiKyt** [comment]
@rufatsamadov user: Current not implemented on linux/arm64

**Comment by sTiKyt** [comment]
#756 Duplicate, closing here

**Comment by rufatsamadov** [comment]
> 
> 
> #756 Duplicate, closing here

where is original?

**Comment by sTiKyt** [comment]
@rufatsamadov i gave you number of original
