### ISSUE TITLE
Problems on MacOS

### ISSUE THREAD

**Issue by KatzeMau** [DarkSecDevelopers/HiddenEye#823]
On Mac, neuwest version hiddeneye and everthing else 
Dont Know how to fix on mac

Last login: Sun Sep 13 18:52:25 on ttys000
(base) tim@MacBook-Pro ~ % cd Downloads
(base) tim@MacBook-Pro Downloads % cd HiddenEye
(base) tim@MacBook-Pro HiddenEye % sudo pip3 install -r requirements.txt
Password:
WARNING: The directory '/Users/tim/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: certifi==2020.6.20 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: future==0.18.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.18.2)
Requirement already satisfied: idna==2.10 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: pyngrok==4.1.10 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (4.1.10)
Requirement already satisfied: PyYAML==5.3.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (5.3.1)
Requirement already satisfied: requests==2.23.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.23.0)
Requirement already satisfied: urllib3==1.25.10 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.25.10)
Collecting pgrep==2020.7.1
  Downloading pgrep-2020.7.1.tar.gz (1.4 kB)
  WARNING: Requested pgrep==2020.7.1 from https://files.pythonhosted.org/packages/04/cd/ac18e02ab47028a85b80abacb770b1432b22c331b6f2240d48d57c1ee313/pgrep-2020.7.1.tar.gz#sha256=277d75948dcbd6200bf0ef6a0fb1082eb9469ffbc9ac5fab613974e8ff62db9d (from -r requirements.txt (line 9)), but installing version 0.0.0
Collecting kill==2020.7.1
  Downloading kill-2020.7.1.tar.gz (1.4 kB)
  WARNING: Requested kill==2020.7.1 from https://files.pythonhosted.org/packages/6e/c9/d7cd13884c502c439d74a3363282051b3a2edea81067fce3c0c203d7a7a3/kill-2020.7.1.tar.gz#sha256=b5fa7440b77f999174916e41eab1589e8c2ac447fb4a4c5837de7e4d04add84f (from -r requirements.txt (line 10)), but installing version 0.0.0
Requirement already satisfied: values in /usr/local/lib/python3.8/site-packages (from kill==2020.7.1->-r requirements.txt (line 10)) (0.0.0)
Building wheels for collected packages: pgrep, kill
  Building wheel for pgrep (setup.py) ... done
  Created wheel for pgrep: filename=pgrep-0.0.0-py3-none-any.whl size=1311 sha256=cf1f7645bda44621e4013ac38e676e1592e6a74171ada8d800c4fafb773bef1b
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-z8jd64uu/wheels/ea/ea/48/8ee7fd27156d56a8d4c2cc3e0582e8b1867018d9b6cbe936ff
  Building wheel for kill (setup.py) ... done
  Created wheel for kill: filename=kill-0.0.0-py3-none-any.whl size=1357 sha256=de0a29801498b7f8f31191de928915a53211cd79baf507f0c4661fed0992ed1f
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-z8jd64uu/wheels/cc/42/46/e2f079eb69095cae6eb094169abf74878dfd2ec0bb5c142532
Successfully built pgrep kill
Installing collected packages: pgrep, kill
  Attempting uninstall: pgrep
    Found existing installation: pgrep 0.0.0
    Uninstalling pgrep-0.0.0:
      Successfully uninstalled pgrep-0.0.0
  Attempting uninstall: kill
    Found existing installation: kill 0.0.0
    Uninstalling kill-0.0.0:
      Successfully uninstalled kill-0.0.0
Successfully installed kill-0.0.0 pgrep-0.0.0
(base) tim@MacBook-Pro HiddenEye % Python3 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 11, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/Users/tim/Downloads/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/Users/tim/Downloads/HiddenEye/Defs/ActionManager/simple_informant.py", line 7, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/Users/tim/Downloads/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 13, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import BytesIO
  File "/Users/tim/Downloads/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 41, in <module>
    from pyngrok import conf as ngrok_conf
ImportError: cannot import name 'conf' from 'pyngrok' (unknown location)
(base) tim@MacBook-Pro HiddenEye %tim

**Comment by KatzeMau** [comment]
Can be closed now !
