### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mateovrb** [DarkSecDevelopers/HiddenEye#828]
After i select the port i get the following error

Traceback (most recent call last):
  File "HiddenEye.py", line 44, in <module>
    server_runner.start_server(port)
  File "/home/vrbs/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_server
    set_php(port=port)
  File "/home/vrbs/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 88, in set_php
    run_background_command(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'

**Comment by mateovrb** [comment]
Fixed it. I didn't launch it using sudo. But now after i select the server i get this.

Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/home/vrbs/Documents/SocialEngineering/Phishing/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/home/vrbs/Documents/SocialEngineering/Phishing/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

**Comment by sTiKyt** [comment]
Closed for same reason as #794
