### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Archie-456** [DarkSecDevelopers/HiddenEye#842]
After entering all information to start phishing (enter port number) receive the following error:
Traceback (most recent call last):
  File "HiddenEye.py", line 44, in <module>
    server_runner.start_server(port)
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_server
    set_php(port=port)
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 91, in set_php
    stderr=DEVNULL,
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php': 'php'

**Comment by kyawsanhta** [comment]
ssh -v -R {your custom domain}:443:localhost:8443 plan@ssh.localhost.run

**Comment by kyawsanhta** [comment]
ssh -v -R {your custom domain}:443:localhost:8443 plan@ssh.localhost.run

**Comment by kyawsanhta** [comment]
[https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent](https://admin.localhost.run/) 

> #841

**Comment by sTiKyt** [comment]
?

**Comment by Archie-456** [comment]
Updated PHP to 7.4 from 7.3.
