### ISSUE TITLE
[BUG]  PYTHON ERROR WHEN ADDING PORT

### ISSUE THREAD

**Issue by jigsaw678** [DarkSecDevelopers/HiddenEye#845]
`[*] Select Port [1-65535]:

 [*] We suggest using ports between [1024-65535] but you still able to choose any ports you want.
                                                        HiddenEye >>>  8080
Traceback (most recent call last):
  File "HiddenEye.py", line 44, in <module>
    server_runner.start_server(port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 102, in start_server
    set_php(port=port)
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 88, in set_php
    run_background_command(
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
$`

**Comment by J213P** [comment]
u have got my same problem
