### ISSUE TITLE
[BUG] i am getting this issue

### ISSUE THREAD

**Issue by jigsaw678** [DarkSecDevelopers/HiddenEye#847]
```
Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'
```

i have ngrok installed but how do i redirect the callback to it

**Comment by E1MWM13** [comment]
> ```
> Traceback (most recent call last):
>   File "HiddenEye.py", line 45, in <module>
>     server_runner.server_selection(port)
>   File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
>     NgrokController().establish_connection(port=port)
>   File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection
>     self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
>   File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
>     api_url = get_ngrok_process(pyngrok_config).api_url
>   File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
>     ensure_ngrok_installed(pyngrok_config.ngrok_path)
> AttributeError: 'str' object has no attribute 'ngrok_path'
> ```
> 
> 
> i have ngrok installed but how do i redirect the callback to it

same bug friends

**Comment by E1MWM13** [comment]
OMG!!! serveo & ngrok is error now i only can use localhost server, but the link error for other people
