### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alari73512** [DarkSecDevelopers/HiddenEye#849]
Hello! im getting this error after choosing ngrok.

Traceback (most recent call last):                                                                 
  File "HiddenEye.py", line 45, in <module>                                                        
    server_runner.server_selection(port)                                                           
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                                                                                
    NgrokController().establish_connection(port=port)                                              
  File "/home/kali/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection    
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)  
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect             
    api_url = get_ngrok_process(pyngrok_config).api_url                                            
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process   
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                                              
AttributeError: 'str' object has no attribute 'ngrok_path'                                         
root@kali:/home/kali/HiddenEye#

**Comment by alari73512** [comment]
and this too Traceback (most recent call last):                                                                 
  File "HiddenEye.py", line 45, in <module>                                                        
    server_runner.server_selection(port)                                                           
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                                                                                
    NgrokController().establish_connection(port=port)                                              
  File "/home/kali/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection    
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)  
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect             
    api_url = get_ngrok_process(pyngrok_config).api_url                                            
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process   
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                                              
AttributeError: 'str' object has no attribute 'ngrok_path'
